internxt/meet-web

Makefile, package-lock.json, package.json
- Added pqc-kem-kyber512.wasm to libs dir on Makefile deploy
- Updated lib-internxt-meet to its fixed version
=> [_]: Fix/PQC kyber512 dependency

react/features/settings/components/web/SettingsDialog.tsx, react/features/toolbox/components/web/Toolbox.tsx, react/features/toolbox/functions.web.ts, react/features/toolbox/types.ts
- It disables unused settings and buttons
=> [_]: feat/disable-unused-settings

react/features/reactions/components/web/RaiseHandContainerButtons.tsx, react/features/toolbox/components/web/Toolbox.tsx
=> [_]: fix/display-filter

react/features/toolbox/functions.web.ts
- Disables virtual background button
=> [_]: feat/disable-virtual-background-button

react/features/toolbox/functions.web.ts
=> [_]: feat/disable-fullscreen-button

react/features/conference/components/native/Labels.tsx, react/features/conference/components/native/carmode/TitleBar.tsx, react/features/toolbox/functions.web.ts
- Disables videoQuality button
=> [_]: feat/disable-video-quality-button

react/features/conference/components/web/ConferenceInfo.tsx
- Disabled videoQuality button
=> [_]: fix/disable-videoQuality-button

lang/main-es.json, lang/main.json, react/features/base/meet/views/PreMeeting/PreMeetingScreen.tsx, react/features/base/meet/views/PreMeeting/components/NameInputSection.tsx, react/features/base/meet/views/PreMeeting/components/ParticipantsList.tsx, react/features/base/meet/views/PreMeeting/components/VideoPreviewSection.tsx, react/features/base/meet/views/PreMeeting/hooks/useParticipants.test.ts, react/features/base/meet/views/PreMeeting/hooks/useParticipants.ts, react/features/base/meet/views/PreMeeting/types/index.ts, react/features/prejoin/components/web/Prejoin.tsx
- Created participants list component and refactor `PremeetingScreen`
-
- https://github.com/internxt/ui/pull/47
-   [x] Unit tests have been written or updated as necessary.
- Logged in and checked the participants are displayed in premeeting screeen
-
=> [PB-3787]: feture/Create participants list component and refactor PremeetingScreen

react/features/base/meet/views/Conference/Conference.tsx
- Moved Conference.tsx file to Meet folder in order to have all related with meet in same directory
- 
-
-
-   [x] No new warnings or errors have been introduced.
- Start a meeting and check that works correctly
-
=> [_] feature/Move Conference file

.eslintrc.js, .gitignore, .npmrc, .npmrc.template, lang/main-es.json, package-lock.json, react/features/base/meet/views/Conference/components/VideoGallery.tsx, react/features/base/meet/views/Conference/components/VideoParticipant.tsx, react/features/base/meet/views/Conference/components/VideoSpeaker.tsx, react/features/base/meet/views/Conference/containers/VideoGalleryWrapper.tsx, react/features/display-name/components/web/StageParticipantNameLabel.tsx, react/features/large-video/components/LargeVideo.web.tsx
Added speaker mode.
I took advantage of this task and removed npmrc file.
=> [PB-3795]:Feat/speaker mode

lang/main-es.json, lang/main.json, react/features/base/meet/views/Conference/components/InviteUser.tsx, react/features/base/meet/views/Conference/containers/ConferenceControlsWrapper.tsx, react/features/base/meet/views/Conference/containers/VideoGalleryWrapper.tsx, react/features/base/meet/views/Conference/utils.ts
=> [PB-3791]:feat/Invite user

lang/main-es.json, lang/main.json, react/features/app/actions.web.ts, react/features/base/meet/constants.ts, react/features/base/meet/views/Conference/Conference.tsx, react/features/base/meet/views/Conference/CreateConference.tsx, react/features/base/meet/views/Conference/components/CreateConference.tsx, react/features/base/meet/views/Conference/components/InviteUser.tsx, react/features/base/meet/views/Conference/components/JoinConference.tsx, react/features/base/meet/views/PreMeeting/PreMeetingScreen.tsx, react/features/base/meet/views/PreMeeting/components/PreMeetingModal.tsx, react/features/prejoin/actionTypes.ts, react/features/prejoin/actions.web.ts, react/features/prejoin/components/web/Prejoin.tsx, react/features/prejoin/reducer.ts, react/features/welcome/components/AbstractWelcomePage.ts, react/features/welcome/components/WelcomePage.web.tsx
Separe joining and creation meeting flows
Create new meeting and notice that screen are different from join a meeting, following Figma designs.
=> [PB-4058]:feat/Separe joining and creation meeting flows

.github/workflows/pr-size-control.yml, .github/workflows/sonarcloud-analysis.yml, .gitignore, sonar-project.properties, vitest.config.ts
This PR introduces two new GitHub Actions to improve code quality and PR management:
- SonarCloud analysis: Executes static code analysis using SonarCloud. Currently configured to scan only the `react/features/base/meet` folder, aligning with active development efforts.
- PR size control: Ensures pull requests remain manageable by limiting their size to a maximum of 500 lines of code (LOCs).
Future adjustments to SonarCloud analysis …
=> [PB-4113]: chore/Sonarcloud analysis and PR-size control

lang/main-es.json, lang/main.json, react/features/base/meet/views/Home/containers/ScheduleModal.tsx
- Created schedule meeting modal component
-
-
-   [x] Unit tests have been written or updated as necessary.
-   [x] Relevant documentation has been added or updated.
-   [x] No new warnings or errors have been introduced.
-   [x] SonarCloud issues have been reviewed and addressed.
- It is not possible to test, only component has been created, you will be able to see in the PR that integrates the modal in the flow.
=> [PB-4231]feature/Create schedule meeting modal

react/features/base/meet/LocalStorageManager.ts, react/features/base/meet/views/Home/containers/AuthModal.tsx, react/features/base/meet/views/Home/hooks/useLoginModal.ts, react/features/base/meet/views/Home/hooks/useSignUp.test.ts, react/features/base/meet/views/Home/hooks/useSignUp.ts
- Added necesssary changes to log in automatically after successful sign up
-
-
-   [x] Unit tests have been written or updated as necessary.
-   [x] Relevant documentation has been added or updated.
-   [x] No new warnings or errors have been introduced.
-   [x] SonarCloud issues have been reviewed and addressed.
- Click on sign up button in home page, fill the sign up form, and after successful sign up the user has to be logged in automatically
-
=> [PB-4265] feature/Handle auto login after sign up

README.md
Updated readme
-
-
-   [x] Relevant documentation has been added or updated.
-   [x] No new warnings or errors have been introduced.
-   [x] SonarCloud issues have been reviewed and addressed.
-
-
=> [PB-4303] feature/Update readme

react/features/base/meet/middlewares/meeting.middleware.ts
Bypass to be able to test meet in beta env without necessary account
-
-
=> [_] feature/Bypass to avoid tier check

package-lock.json, react/features/base/meet/views/PreMeeting/PreMeetingScreen.tsx
- Changed encoding toggle position and added package lock updated
=> [_] feature/Change encoding toggle position

lang/main-es.json, lang/main.json, react/features/base/meet/views/Settings/SettingsDialog.tsx, react/features/base/meet/views/Settings/SettingsDialogWrapper.tsx
- Added Account section in new Settings modal
- Log in, open the Settings modal and check that the manage account section it opens the drive account section
=> [PB-4458] feature/Include in the modal of setting the Account section

react/features/base/meet/views/Settings/CustomDeviceSelector.tsx, react/features/base/meet/views/Settings/SettingsDialog.tsx
- Change dropdown arrow direction
- Open Settings and check that drowpdown arrow icon
=> [_] feature/minor design change

.github/workflows/publish.yml, react/features/base/meet/services/__tests__/sdk-manager.service.test.ts, react/features/base/meet/services/types/config.types.ts
Migrate publish action to gateway enpdoints
- Check that meet works (login, enter to a call, sign up)
=> Removed old drive-server env and migrated deploy to gateway endpoints

react/features/base/media/components/web/Video.tsx, react/features/base/meet/constants.ts, react/features/base/meet/services/config.service.ts, react/features/base/meet/views/Conference/components/VideoParticipant.tsx, react/features/base/meet/views/Conference/containers/ConferenceControlsWrapper.tsx, react/features/base/meet/views/PreMeeting/PreMeetingScreen.tsx, react/features/conference/components/web/ConferenceInfo.tsx, react/features/e2ee/middleware.ts
- Added development environment check to hide dev elements
-
-
-   [x] QA Passed
- Check that development elements are not shown in production version and encoding is always enabled
=> [PB-4994] feature/Hide develpment UI elements in production build

react/features/base/meet/general/containers/MeetingButton.tsx, react/features/base/meet/views/Home/HomePage.tsx, react/features/base/meet/views/Home/containers/HeaderWrapper.tsx, react/features/base/meet/views/Home/containers/ScheduleModal.tsx
Changed home page to fit new design and flow
-
-
Enter to home page and check that fits figma design and flow
=> [PB-4956] feature/Update Home Page Buttons and Popup Design

.github/workflows/publish.yml
- Modified publish action to add preview link in the PR as comment
- Check that cloudflare preview link of current PR is published in a comment correctly
=> [_] feature/Public preview link in a comment
